# Generated by Django 5.1.1 on 2024-11-16 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFuente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('is_monitoring', models.BooleanField()),
                ('editores', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('url', models.CharField()),
            ],
            options={
                'db_table': 'api_fuente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjeTematico',
            fields=[
                ('id_eje', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_eje', models.CharField(blank=True, max_length=60, null=True)),
                ('esta_activo', models.BooleanField()),
            ],
            options={
                'db_table': 'eje_tematico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiPatente',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('claims', models.TextField()),
                ('patent_office', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.apifuente')),
            ],
            options={
                'db_table': 'api_patente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRegistros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.JSONField()),
                ('metadata', models.JSONField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.apifuente')),
            ],
            options={
                'db_table': 'api_registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='boletines/imagenes/')),
                ('labels', models.JSONField(blank=True, null=True)),
                ('attached_document', models.FileField(blank=True, null=True, upload_to='boletines/documentos/')),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_publicados', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines', to='api.ejetematico')),
            ],
            options={
                'db_table': 'boletines',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddField(
            model_name='apifuente',
            name='id_eje',
            field=models.ForeignKey(db_column='id_eje', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejetematico'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('observador', 'Observador'), ('directivo', 'Directivo')], default='user', max_length=10)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
             options={
                'db_table': 'api_userprofile',
                'managed': False,
            },
        ),
    ]
