# Generated by Django 5.1.1 on 2024-09-29 01:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFuente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('is_monitoring', models.BooleanField()),
                ('editores', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('url', models.CharField()),
            ],
            options={
                'db_table': 'api_fuente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiPatente',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('claims', models.TextField()),
                ('patent_office', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'api_patente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRegistros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.JSONField()),
                ('metadata', models.JSONField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
            ],
            options={
                'db_table': 'api_registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjeTematico',
            fields=[
                ('id_eje', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_eje', models.CharField(blank=True, max_length=60, null=True)),
                ('esta_activo', models.BooleanField()),
            ],
            options={
                'db_table': 'eje_tematico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('observador', 'Observador'), ('user', 'User')], max_length=50)),
                ('organization', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
