# Generated by Django 5.0.2 on 2024-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('claims', models.TextField()),
                ('patent_office', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
