# Generated by Django 5.0.2 on 2024-03-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='patente',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fuente'),
        ),
        migrations.AddField(
            model_name='registros',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fuente'),
        ),
    ]
