# Generated by Django 5.0.6 on 2024-05-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patente_fuente_registros_fuente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='ejesTematicos',
            new_name='id_eje',
        ),
    ]
