# Generated by Django 5.1.1 on 2024-09-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_ejestematicos_fuente_id_eje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFuente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('is_monitoring', models.BooleanField()),
                ('editores', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('url', models.CharField()),
            ],
            options={
                'db_table': 'api_fuente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiPatente',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('description', models.TextField()),
                ('claims', models.TextField()),
                ('patent_office', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'api_patente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRegistros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.JSONField()),
                ('metadata', models.JSONField()),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
            ],
            options={
                'db_table': 'api_registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjeTematico',
            fields=[
                ('id_eje', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_eje', models.CharField(blank=True, max_length=60, null=True)),
                ('esta_activo', models.BooleanField()),
            ],
            options={
                'db_table': 'eje_tematico',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='patente',
            name='fuente',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='registros',
        ),
        migrations.DeleteModel(
            name='fuente',
        ),
        migrations.DeleteModel(
            name='Patente',
        ),
    ]
